service:
  name: board
#app: your-app-name
#tenant: your-tenant-name

# Add the serverless-webpack plugin
plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  environment:
    SLS_DEBUG: true

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          method: get
          path: hello
