service:
  name: board
#app: your-app-name
#tenant: your-tenant-name

# Add the serverless-webpack plugin
plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  environment:
    SLS_DEBUG: true

functions:
  graphql:
    handler: src/handler.graphql
    events:
      - http:
          path: graphql
          method: any
          timeout: 30
          integration: lambda-proxy
          cors: true